import "./globals.css";
import Wrappper from "./wrappper";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="bg-[#f4f2ee]">
				<Wrappper>
					{children}
				</Wrappper>
			</body>
		</html>
	);
}
